# Açık Pozisyonlar tablosu için SQL (MySQL eski sürüm uyumlu)
CREATE TABLE IF NOT EXISTS `open_positions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `symbol` varchar(20) NOT NULL,
  `type` varchar(10) NOT NULL DEFAULT 'LONG',
  `entry_price` decimal(20,8) NOT NULL,
  `amount` decimal(20,8) NOT NULL,
  `entry_time` datetime NOT NULL,
  `stop_loss` decimal(20,8) DEFAULT NULL,
  `take_profit` decimal(20,8) DEFAULT NULL,
  `strategy` varchar(50) DEFAULT NULL,
  `leverage` int(11) DEFAULT 1,
  `trade_mode` varchar(10) DEFAULT 'paper',
  `risk_level` varchar(20) DEFAULT NULL,
  `risk_factors` text,
  `trade_amount_usd` decimal(20,2) DEFAULT NULL,
  `status` varchar(10) DEFAULT 'open',
  `close_price` decimal(20,8) DEFAULT NULL,
  `close_time` datetime NULL DEFAULT NULL,
  `profit_loss` decimal(20,8) DEFAULT NULL,
  `profit_loss_pct` decimal(10,4) DEFAULT NULL,
  `close_reason` varchar(50) DEFAULT NULL,
  `notes` text,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `symbol` (`symbol`),
  KEY `status` (`status`),
  KEY `entry_time` (`entry_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;